### ISSUE TITLE
liborx.so: cannot open shared object file

### ISSUE THREAD

**Issue by mwcz** [Arc676/SpammerTyper#1]
I see this error when I try to run the game on Fedora 28.

```
$ ./SpammerTyper
./SpammerTyper: error while loading shared libraries: liborx.so: cannot open shared object file: No such file or directory
```

I see it in both the packaged build and when I build it myself.  I'll try copying liborx into an existing lib path and see if that helps.

**Comment by mwcz** [comment]
There we go!  I got it to run with:

```
LD_LIBRARY_PATH="./" ./SpammerTyper
```

(run from the directory I extracted the game into)

I'll add this to the comments on itch also, in case it helps anyone else.

**Comment by Arc676** [comment]
You're right, I had forgotten about this step. I'll add it to the README.
